version: '3.8'

services:
# Servicio Samba
  samba:
    image: lordpedal/samba
    container_name: SAMBA
    environment:
      - TZ=${TZ}
    volumes:
      - ${MEDIA}:/media
      - ${STORAGE}/torrents:/downloads
    ports:
      - 139:139
      - 445:445
    restart: always
#--------------------------------------------------------------------#
# Servicio Plex
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: PLEX
    environment:
      - TZ=${TZ}
      - VERSION=docker
    volumes:
      - ${STORAGE}/Plex Media Server:/root/Library/Application Support/Plex Media Server
      - ${MEDIA}:/media
      - ${STORAGE}/tmp:/tmp
    expose:
      - 32401
      - 33401
    restart: unless-stopped
    network_mode: "host"
#--------------------------------------------------------------------#
# Servicio Transmission
  transmission:
    image : jaymoulin/transmission:3.00-1.6.1
    container_name: TORRENTBT
    command: transmission-daemon -f -g /config
    volumes:
      - ./transmission:/config
      - ${STORAGE}/torrents:/downloads
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    expose:
      - 9091
    restart: unless-stopped
