version: '3.8'

services:
# Servicio Plex
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: PLEX
    environment:
      - TZ=${TZ}
      - VERSION=docker
    volumes:
      - ${SHARED}/Plex Media Server:/root/Library/Application Support/Plex Media Server
      - ${SHARED}:/media
      - ${SHARED}/tmp:/tmp
    expose:
      - 32401
      - 33401
    restart: unless-stopped
    network_mode: "host"
#--------------------------------------------------------------------#
# Servicio Transmission
  transmission:
    image : jaymoulin/transmission:3.00-1.6.1
    container_name: TORRENTBT
    command: transmission-daemon -f -g /config
    volumes:
      - ${SHARED}./transmission:/config
      - ${SHARED}/torrents:/downloads
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    expose:
      - 9091
    restart: unless-stopped
