version: '3.8'

services:
  samba:
    image: dperson/samba
    container_name: SAMBA
    command: '-u "${SAMBA_USER};${SAMBA_PASSWORD}" -s "media;/media;yes;no" -s "downloads;/downloads;yes;no"'
    tty: true
    environment:
      - TZ=${TZ}
      - SAMBA_USER=${SAMBA_USER}
      - SAMBA_PASSWORD=${SAMBA_PASSWORD}
    volumes:
      - ${MEDIA}:/media
      - ${STORAGE}/torrents:/downloads
    ports:
      - 139:139
      - 445:445
    restart: always
#--------------------------------------------------------------------#
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: PLEX
    environment:
      - TZ=${TZ}
      - VERSION=docker
    volumes:
      - ${MEDIA}:/media
      - ${STORAGE}/tmp:/tmp
      - ${STORAGE}/Plex Media Server:/root/Library/Application Support/Plex Media Server
    expose:
      - 32401
      - 33401
    restart: unless-stopped
    network_mode: "host"
#--------------------------------------------------------------------#
  transmission:
    image : jaymoulin/transmission:3.00-1.6.1
    container_name: TORRENTBT
    command: transmission-daemon -f -g /config
    volumes:
      - ./transmission:/config
      - ${STORAGE}/torrents:/downloads
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    expose:
      - 9091
    restart: unless-stopped
