---
services:
  samba:
    image: dperson/samba
    container_name: SAMBA
    command: '-u "${USER};${PASS}" -s "media;/media;yes;no" -s "downloads;/downloads;yes;no"'
    tty: true
    environment:
      - TZ=${TZ}
      - USER=${USER}
      - PASS=${PASS}
    volumes:
      - ${MEDIA}:/media
      - ${STORAGE}/torrents:/downloads
    ports:
      - 139:139
      - 445:445
    restart: always
#--------------------------------------------------------------------#
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: PLEX
    environment:
      - TZ=${TZ}
      - VERSION=docker
    volumes:
      - ${MEDIA}:/media
      - ${STORAGE}/tmp:/tmp
      - ${STORAGE}/Plex Media Server:/root/Library/Application Support/Plex Media Server
    expose:
     - 32400
     - 33400
    restart: unless-stopped
    network_mode: "host"
#--------------------------------------------------------------------#
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: TORRENT
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - USER=${USER}
      - PASS=${PASS}
    volumes:
      - ./transmission:/config
      - ${STORAGE}/torrents:/downloads
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
